services: 
  php:
    image: dockerfile
    container_name: php
    ports:
      - "8000:80"
    volumes:
      - .:/var/wwww/html
  mysql: 
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"

    

    
    